import { NextResponse } from 'next/server';
import { Client } from 'ssh2';

const DEFAULT_SERVERS = [
  { host: '167.172.51.232', username: 'root' },
  { host: '167.99.90.211', username: 'root' },
  { host: '46.101.86.238', username: 'root' },
  { host: '138.68.153.135', username: 'root' },
  { host: '188.166.159.196', username: 'root' },
  { host: '46.101.78.167', username: 'root' }
];

const PYTHON_SCRIPT_B64 = "ZnJvbSBEcmlzc2lvblBhZ2UgaW1wb3J0IENocm9taXVtUGFnZSwgQ2hyb21pdW1PcHRpb25zCmltcG9ydCBzeXMsIHRpbWUsIHJhbmRvbSwgdGhyZWFkaW5nLCBqc29uLCBvcwoKdmlzaXRfY291bnQgPSAwCmVycm9yX2NvdW50ID0gMApsb2NrID0gdGhyZWFkaW5nLkxvY2soKQpTVEFUVVNfRklMRSA9ICIvcm9vdC92aXNpdF9zdGF0dXMuanNvbiIKClVTRVJfQUdFTlRTID0gWwogICAgJ01vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNicsCiAgICAnTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMS4wLjAuMCBTYWZhcmkvNTM3LjM2JywKICAgICdNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMS4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIyLjAuMC4wIFNhZmFyaS81MzcuMzYnLAogICAgJ01vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNicsCiAgICAnTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTIzLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTIzLjAnLAogICAgJ01vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi8xNy4yIFNhZmFyaS82MDUuMS4xNScsCiAgICAnTW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxN18zIGxpa2UgTWFjIE9TIFgpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi8xNy4yIE1vYmlsZS8xNUUxNDggU2FmYXJpLzYwNC4xJywKICAgICdNb3ppbGxhLzUuMCAoTGludXg7IEFuZHJvaWQgMTQ7IFNNLVM5MThCKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTIyLjAuMC4wIE1vYmlsZSBTYWZhcmkvNTM3LjM2JywKICAgICdNb3ppbGxhLzUuMCAoaVBhZDsgQ1BVIE9TIDE3XzMgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE3LjIgTW9iaWxlLzE1RTE0OCBTYWZhcmkvNjA0LjEnLAogICAgJ01vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNiBFZGcvMTIyLjAuMC4wJywKICAgICdNb3ppbGxhLzUuMCAoWDExOyBMaW51eCB4ODZfNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjIuMC4wLjAgU2FmYXJpLzUzNy4zNicsCiAgICAnTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyMC4wLjAuMCBTYWZhcmkvNTM3LjM2JywKXQoKUkVGRVJSRVJTID0gWwogICAgJ2h0dHBzOi8vd3d3Lmdvb2dsZS5jb20vJywKICAgICdodHRwczovL3d3dy5nb29nbGUuY29tL3NlYXJjaD9xPScsCiAgICAnaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS5zYS9zZWFyY2g/cT0nLAogICAgJ2h0dHBzOi8vd3d3LmZhY2Vib29rLmNvbS8nLAogICAgJ2h0dHBzOi8vdC5jby8nLAogICAgJ2h0dHBzOi8vd3d3Lmluc3RhZ3JhbS5jb20vJywKICAgICdodHRwczovL3d3dy55b3V0dWJlLmNvbS8nLAogICAgJ2h0dHBzOi8vd3d3LnRpa3Rvay5jb20vJywKICAgICdodHRwczovL3d3dy5zbmFwY2hhdC5jb20vJywKICAgICdodHRwczovL3d3dy5saW5rZWRpbi5jb20vJywKICAgICcnLCAgIyBkaXJlY3QgdmlzaXQKICAgICcnLCAgIyBkaXJlY3QgdmlzaXQKXQoKU0NSRUVOX1JFU09MVVRJT05TID0gWwogICAgKDE5MjAsIDEwODApLCAoMTM2NiwgNzY4KSwgKDE1MzYsIDg2NCksICgxNDQwLCA5MDApLAogICAgKDEyODAsIDcyMCksICgyNTYwLCAxNDQwKSwgKDE2MDAsIDkwMCksICgxMjgwLCA4MDApLAogICAgKDM5MCwgODQ0KSwgKDQxNCwgODk2KSwgKDM3NSwgODEyKSwgKDQyOCwgOTI2KSwgICMgbW9iaWxlCl0KCkxBTkdVQUdFUyA9IFsKICAgICdhci1TQSxhcjtxPTAuOSxlbjtxPTAuOCcsCiAgICAnYXIsZW4tVVM7cT0wLjksZW47cT0wLjgnLAogICAgJ2FyLVNBLGFyO3E9MC45LGVuLVVTO3E9MC44LGVuO3E9MC43JywKICAgICdlbi1VUyxlbjtxPTAuOSxhcjtxPTAuOCcsCiAgICAnYXItRUcsYXI7cT0wLjksZW47cT0wLjgnLApdCgpUSU1FWk9ORVMgPSBbCiAgICAnQXNpYS9SaXlhZGgnLCAnQXNpYS9EdWJhaScsICdBc2lhL0t1d2FpdCcsCiAgICAnQXNpYS9CYWhyYWluJywgJ0FzaWEvUWF0YXInLApdCgojIEphdmFTY3JpcHQgdG8gaW5qZWN0IC0gaGlkZXMgYWxsIGF1dG9tYXRpb24gdHJhY2VzClNURUFMVEhfSlMgPSAiIiIKLy8gSGlkZSB3ZWJkcml2ZXIKT2JqZWN0LmRlZmluZVByb3BlcnR5KG5hdmlnYXRvciwgJ3dlYmRyaXZlcicsIHtnZXQ6ICgpID0+IHVuZGVmaW5lZH0pOwpkZWxldGUgbmF2aWdhdG9yLl9fcHJvdG9fXy53ZWJkcml2ZXI7CgovLyBIaWRlIGF1dG9tYXRpb24Kd2luZG93LmNocm9tZSA9IHtydW50aW1lOiB7fSwgbG9hZFRpbWVzOiBmdW5jdGlvbigpe3JldHVybiB7fX0sIGNzaTogZnVuY3Rpb24oKXtyZXR1cm4ge319fTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KG5hdmlnYXRvciwgJ3BsdWdpbnMnLCB7Z2V0OiAoKSA9PiBbCiAgICB7bmFtZTogJ0Nocm9tZSBQREYgUGx1Z2luJywgZmlsZW5hbWU6ICdpbnRlcm5hbC1wZGYtdmlld2VyJ30sCiAgICB7bmFtZTogJ0Nocm9tZSBQREYgVmlld2VyJywgZmlsZW5hbWU6ICdtaGpmYm1kZ2NmamJicGFlb2pvZm9ob2VmZ2llaGphaSd9LAogICAge25hbWU6ICdOYXRpdmUgQ2xpZW50JywgZmlsZW5hbWU6ICdpbnRlcm5hbC1uYWNsLXBsdWdpbid9Cl19KTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KG5hdmlnYXRvciwgJ2xhbmd1YWdlcycsIHtnZXQ6ICgpID0+IFsnYXInLCAnZW4tVVMnLCAnZW4nXX0pOwpPYmplY3QuZGVmaW5lUHJvcGVydHkobmF2aWdhdG9yLCAncGxhdGZvcm0nLCB7Z2V0OiAoKSA9PiAnV2luMzInfSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdoYXJkd2FyZUNvbmN1cnJlbmN5Jywge2dldDogKCkgPT4gX19DT1JFU19ffSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShuYXZpZ2F0b3IsICdkZXZpY2VNZW1vcnknLCB7Z2V0OiAoKSA9PiBfX01FTU9SWV9ffSk7CgovLyBIaWRlIGhlYWRsZXNzIGluZGljYXRvcnMKT2JqZWN0LmRlZmluZVByb3BlcnR5KG5hdmlnYXRvciwgJ21heFRvdWNoUG9pbnRzJywge2dldDogKCkgPT4gX19UT1VDSF9ffSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICd3aWR0aCcsIHtnZXQ6ICgpID0+IF9fU1dfX30pOwpPYmplY3QuZGVmaW5lUHJvcGVydHkoc2NyZWVuLCAnaGVpZ2h0Jywge2dldDogKCkgPT4gX19TSF9ffSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICdhdmFpbFdpZHRoJywge2dldDogKCkgPT4gX19TV19ffSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICdhdmFpbEhlaWdodCcsIHtnZXQ6ICgpID0+IF9fU0hfXyAtIDQwfSk7Ck9iamVjdC5kZWZpbmVQcm9wZXJ0eShzY3JlZW4sICdjb2xvckRlcHRoJywge2dldDogKCkgPT4gMjR9KTsKCi8vIEZha2UgcGVybWlzc2lvbnMgQVBJCmNvbnN0IG9yaWdpbmFsUXVlcnkgPSB3aW5kb3cubmF2aWdhdG9yLnBlcm1pc3Npb25zLnF1ZXJ5Owp3aW5kb3cubmF2aWdhdG9yLnBlcm1pc3Npb25zLnF1ZXJ5ID0gKHBhcmFtZXRlcnMpID0+ICgKICAgIHBhcmFtZXRlcnMubmFtZSA9PT0gJ25vdGlmaWNhdGlvbnMnID8KICAgIFByb21pc2UucmVzb2x2ZSh7c3RhdGU6IE5vdGlmaWNhdGlvbi5wZXJtaXNzaW9ufSkgOgogICAgb3JpZ2luYWxRdWVyeShwYXJhbWV0ZXJzKQopOwoKLy8gRmFrZSBXZWJHTCB2ZW5kb3IKY29uc3QgZ2V0UGFyYW1ldGVyID0gV2ViR0xSZW5kZXJpbmdDb250ZXh0LnByb3RvdHlwZS5nZXRQYXJhbWV0ZXI7CldlYkdMUmVuZGVyaW5nQ29udGV4dC5wcm90b3R5cGUuZ2V0UGFyYW1ldGVyID0gZnVuY3Rpb24ocGFyYW1ldGVyKSB7CiAgICBpZiAocGFyYW1ldGVyID09PSAzNzQ0NSkgcmV0dXJuICdJbnRlbCBJbmMuJzsKICAgIGlmIChwYXJhbWV0ZXIgPT09IDM3NDQ2KSByZXR1cm4gJ0ludGVsIElyaXMgT3BlbkdMIEVuZ2luZSc7CiAgICByZXR1cm4gZ2V0UGFyYW1ldGVyLmNhbGwodGhpcywgcGFyYW1ldGVyKTsKfTsKCi8vIEZha2UgY2FudmFzIGZpbmdlcnByaW50CmNvbnN0IHRvRGF0YVVSTCA9IEhUTUxDYW52YXNFbGVtZW50LnByb3RvdHlwZS50b0RhdGFVUkw7CkhUTUxDYW52YXNFbGVtZW50LnByb3RvdHlwZS50b0RhdGFVUkwgPSBmdW5jdGlvbih0eXBlKSB7CiAgICBpZiAodHlwZSA9PT0gJ2ltYWdlL3BuZycgJiYgdGhpcy53aWR0aCA+IDE2ICYmIHRoaXMuaGVpZ2h0ID4gMTYpIHsKICAgICAgICBjb25zdCBjdHggPSB0aGlzLmdldENvbnRleHQoJzJkJyk7CiAgICAgICAgaWYgKGN0eCkgewogICAgICAgICAgICBjb25zdCBub2lzZSA9IE1hdGgucmFuZG9tKCkgKiAwLjAxOwogICAgICAgICAgICBjdHguZ2xvYmFsQWxwaGEgPSAxIC0gbm9pc2U7CiAgICAgICAgfQogICAgfQogICAgcmV0dXJuIHRvRGF0YVVSTC5hcHBseSh0aGlzLCBhcmd1bWVudHMpOwp9OwoKLy8gRmFrZSBBdWRpb0NvbnRleHQgZmluZ2VycHJpbnQKY29uc3Qgb3JpZ0dldENoYW5uZWxEYXRhID0gQXVkaW9CdWZmZXIucHJvdG90eXBlLmdldENoYW5uZWxEYXRhOwpBdWRpb0J1ZmZlci5wcm90b3R5cGUuZ2V0Q2hhbm5lbERhdGEgPSBmdW5jdGlvbihjaGFubmVsKSB7CiAgICBjb25zdCBkYXRhID0gb3JpZ0dldENoYW5uZWxEYXRhLmNhbGwodGhpcywgY2hhbm5lbCk7CiAgICBpZiAoZGF0YS5sZW5ndGggPiAxMDApIHsKICAgICAgICBmb3IgKGxldCBpID0gMDsgaSA8IE1hdGgubWluKDEwLCBkYXRhLmxlbmd0aCk7IGkrKykgewogICAgICAgICAgICBkYXRhW2ldID0gZGF0YVtpXSArIChNYXRoLnJhbmRvbSgpICogMC4wMDAxIC0gMC4wMDAwNSk7CiAgICAgICAgfQogICAgfQogICAgcmV0dXJuIGRhdGE7Cn07CiIiIgoKZGVmIHdyaXRlX3N0YXR1cyhtYXhfdmlzaXRvcnMsIHN0YXJ0X3RpbWUsIHN0YXR1cz0icnVubmluZyIpOgogICAgZ2xvYmFsIHZpc2l0X2NvdW50LCBlcnJvcl9jb3VudAogICAgZWxhcHNlZCA9IGludCh0aW1lLnRpbWUoKSAtIHN0YXJ0X3RpbWUpCiAgICBwcm9ncmVzcyA9IG1pbigxMDAsIHJvdW5kKCh2aXNpdF9jb3VudCAvIG1heF92aXNpdG9ycykgKiAxMDAsIDEpKSBpZiBtYXhfdmlzaXRvcnMgPiAwIGVsc2UgMAogICAgZGF0YSA9IHsKICAgICAgICAic3RhdHVzIjogc3RhdHVzLAogICAgICAgICJ2aXNpdHMiOiB2aXNpdF9jb3VudCwKICAgICAgICAidGFyZ2V0IjogbWF4X3Zpc2l0b3JzLAogICAgICAgICJwcm9ncmVzcyI6IHByb2dyZXNzLAogICAgICAgICJlbGFwc2VkIjogZWxhcHNlZCwKICAgICAgICAiZXJyb3JzIjogZXJyb3JfY291bnQsCiAgICAgICAgInRpbWVzdGFtcCI6IGludCh0aW1lLnRpbWUoKSkKICAgIH0KICAgIHRyeToKICAgICAgICB3aXRoIG9wZW4oU1RBVFVTX0ZJTEUsICJ3IikgYXMgZjoKICAgICAgICAgICAganNvbi5kdW1wKGRhdGEsIGYpCiAgICBleGNlcHQ6CiAgICAgICAgcGFzcwoKZGVmIGNyZWF0ZV9icm93c2VyKHByb3h5PU5vbmUpOgogICAgY28gPSBDaHJvbWl1bU9wdGlvbnMoKQogICAgY28uaGVhZGxlc3MoKQogICAgY28uYXV0b19wb3J0KCkKICAgIAogICAgIyBCYXNpYyBDaHJvbWUgZmxhZ3MKICAgIGNvLnNldF9hcmd1bWVudCgnLS1uby1zYW5kYm94JykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWdwdScpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1kZXYtc2htLXVzYWdlJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWV4dGVuc2lvbnMnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLW5vLWZpcnN0LXJ1bicpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tbXV0ZS1hdWRpbycpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tanMtZmxhZ3M9LS1tYXgtb2xkLXNwYWNlLXNpemU9MTI4JykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLXNvZnR3YXJlLXJhc3Rlcml6ZXInKQogICAgCiAgICAjIEFOVEktREVURUNUSU9OOiBIaWRlIGF1dG9tYXRpb24KICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWJsaW5rLWZlYXR1cmVzPUF1dG9tYXRpb25Db250cm9sbGVkJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWZlYXR1cmVzPUlzb2xhdGVPcmlnaW5zLHNpdGUtcGVyLXByb2Nlc3MnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWRpc2FibGUtaW5mb2JhcnMnKQogICAgY28uc2V0X2FyZ3VtZW50KCctLWRpc2FibGUtYmFja2dyb3VuZC10aW1lci10aHJvdHRsaW5nJykKICAgIGNvLnNldF9hcmd1bWVudCgnLS1kaXNhYmxlLWJhY2tncm91bmRpbmctb2NjbHVkZWQtd2luZG93cycpCiAgICBjby5zZXRfYXJndW1lbnQoJy0tZGlzYWJsZS1yZW5kZXJlci1iYWNrZ3JvdW5kaW5nJykKICAgIAogICAgIyBSYW5kb20gd2luZG93IHNpemUKICAgIHJlcyA9IHJhbmRvbS5jaG9pY2UoU0NSRUVOX1JFU09MVVRJT05TKQogICAgY28uc2V0X2FyZ3VtZW50KGYnLS13aW5kb3ctc2l6ZT17cmVzWzBdfSx7cmVzWzFdfScpCiAgICAKICAgICMgUmFuZG9tIGxhbmd1YWdlCiAgICBsYW5nID0gcmFuZG9tLmNob2ljZShMQU5HVUFHRVMpCiAgICBjby5zZXRfYXJndW1lbnQoZictLWxhbmc9e2xhbmcuc3BsaXQoIiwiKVswXX0nKQogICAgY28uc2V0X2FyZ3VtZW50KGYnLS1hY2NlcHQtbGFuZz17bGFuZ30nKQogICAgCiAgICAjIFJhbmRvbSB0aW1lem9uZQogICAgdHogPSByYW5kb20uY2hvaWNlKFRJTUVaT05FUykKICAgIG9zLmVudmlyb25bJ1RaJ10gPSB0egogICAgCiAgICAjIFVzZXIgYWdlbnQKICAgIHVhID0gcmFuZG9tLmNob2ljZShVU0VSX0FHRU5UUykKICAgIGNvLnNldF91c2VyX2FnZW50KHVhKQogICAgCiAgICAjIFByb3h5CiAgICBpZiBwcm94eToKICAgICAgICBwcm94eV9zdHIgPSBmJ3twcm94eVsiaG9zdCJdfTp7cHJveHlbInBvcnQiXX0nCiAgICAgICAgY28uc2V0X2FyZ3VtZW50KGYnLS1wcm94eS1zZXJ2ZXI9e3Byb3h5X3N0cn0nKQogICAgCiAgICB0cnk6CiAgICAgICAgcGFnZSA9IENocm9taXVtUGFnZShhZGRyX29yX29wdHM9Y28pCiAgICAgICAgCiAgICAgICAgIyBJbmplY3Qgc3RlYWx0aCBKUyBiZWZvcmUgYW55IHBhZ2UgbG9hZAogICAgICAgIGlzX21vYmlsZSA9ICdpUGhvbmUnIGluIHVhIG9yICdBbmRyb2lkJyBpbiB1YSBvciAnaVBhZCcgaW4gdWEKICAgICAgICBjb3JlcyA9IHJhbmRvbS5jaG9pY2UoWzQsIDgsIDEyLCAxNl0pCiAgICAgICAgbWVtb3J5ID0gcmFuZG9tLmNob2ljZShbNCwgOCwgMTZdKQogICAgICAgIHRvdWNoID0gcmFuZG9tLnJhbmRpbnQoMSwgNSkgaWYgaXNfbW9iaWxlIGVsc2UgMAogICAgICAgIAogICAgICAgIGpzID0gU1RFQUxUSF9KUy5yZXBsYWNlKCdfX1NXX18nLCBzdHIocmVzWzBdKSkKICAgICAgICBqcyA9IGpzLnJlcGxhY2UoJ19fU0hfXycsIHN0cihyZXNbMV0pKQogICAgICAgIGpzID0ganMucmVwbGFjZSgnX19DT1JFU19fJywgc3RyKGNvcmVzKSkKICAgICAgICBqcyA9IGpzLnJlcGxhY2UoJ19fTUVNT1JZX18nLCBzdHIobWVtb3J5KSkKICAgICAgICBqcyA9IGpzLnJlcGxhY2UoJ19fVE9VQ0hfXycsIHN0cih0b3VjaCkpCiAgICAgICAgCiAgICAgICAgdHJ5OgogICAgICAgICAgICBwYWdlLnJ1bl9qcyhqcykKICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgIHBhc3MKICAgICAgICAKICAgICAgICByZXR1cm4gcGFnZQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHByaW50KGYiQnJvd3NlciBlcnJvcjoge2V9IiwgZmx1c2g9VHJ1ZSkKICAgICAgICByZXR1cm4gTm9uZQoKZGVmIGh1bWFuX2JlaGF2aW9yKHBhZ2UpOgogICAgIiIiU2ltdWxhdGUgaHVtYW4tbGlrZSBiZWhhdmlvciBvbiB0aGUgcGFnZSIiIgogICAgdHJ5OgogICAgICAgICMgV2FpdCBmb3IgcGFnZSB0byBmdWxseSBsb2FkIChoYW5kbGVzIENsb3VkZmxhcmUgNXMgY2hhbGxlbmdlKQogICAgICAgIHRpbWUuc2xlZXAocmFuZG9tLnVuaWZvcm0oMiwgNCkpCiAgICAgICAgCiAgICAgICAgIyBSYW5kb20gc2Nyb2xsIGRvd24KICAgICAgICBzY3JvbGxfdGltZXMgPSByYW5kb20ucmFuZGludCgxLCAzKQogICAgICAgIGZvciBfIGluIHJhbmdlKHNjcm9sbF90aW1lcyk6CiAgICAgICAgICAgIHNjcm9sbF9hbW91bnQgPSByYW5kb20ucmFuZGludCgxMDAsIDUwMCkKICAgICAgICAgICAgcGFnZS5ydW5fanMoZid3aW5kb3cuc2Nyb2xsQnkoMCwge3Njcm9sbF9hbW91bnR9KScpCiAgICAgICAgICAgIHRpbWUuc2xlZXAocmFuZG9tLnVuaWZvcm0oMC4zLCAwLjgpKQogICAgICAgIAogICAgICAgICMgUmFuZG9tIHNjcm9sbCB1cCBhIGJpdAogICAgICAgIGlmIHJhbmRvbS5yYW5kb20oKSA+IDAuNToKICAgICAgICAgICAgcGFnZS5ydW5fanMoZid3aW5kb3cuc2Nyb2xsQnkoMCwgLXtyYW5kb20ucmFuZGludCg1MCwgMjAwKX0pJykKICAgICAgICAgICAgdGltZS5zbGVlcChyYW5kb20udW5pZm9ybSgwLjIsIDAuNSkpCiAgICAgICAgCiAgICAgICAgIyBTaW11bGF0ZSBtb3VzZSBtb3ZlbWVudCB2aWEgSlMKICAgICAgICBwYWdlLnJ1bl9qcygnJycKICAgICAgICAgICAgdmFyIGV2dCA9IG5ldyBNb3VzZUV2ZW50KCdtb3VzZW1vdmUnLCB7CiAgICAgICAgICAgICAgICBjbGllbnRYOiBNYXRoLnJhbmRvbSgpICogd2luZG93LmlubmVyV2lkdGgsCiAgICAgICAgICAgICAgICBjbGllbnRZOiBNYXRoLnJhbmRvbSgpICogd2luZG93LmlubmVySGVpZ2h0LAogICAgICAgICAgICAgICAgYnViYmxlczogdHJ1ZQogICAgICAgICAgICB9KTsKICAgICAgICAgICAgZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChldnQpOwogICAgICAgICcnJykKICAgICAgICAKICAgICAgICAjIFJhbmRvbSBjbGljayBvbiBwYWdlIGJvZHkgKG5vdCBsaW5rcykKICAgICAgICBpZiByYW5kb20ucmFuZG9tKCkgPiAwLjY6CiAgICAgICAgICAgIHBhZ2UucnVuX2pzKCcnJwogICAgICAgICAgICAgICAgdmFyIGV2dCA9IG5ldyBNb3VzZUV2ZW50KCdjbGljaycsIHsKICAgICAgICAgICAgICAgICAgICBjbGllbnRYOiBNYXRoLnJhbmRvbSgpICogd2luZG93LmlubmVyV2lkdGggKiAwLjggKyB3aW5kb3cuaW5uZXJXaWR0aCAqIDAuMSwKICAgICAgICAgICAgICAgICAgICBjbGllbnRZOiBNYXRoLnJhbmRvbSgpICogd2luZG93LmlubmVySGVpZ2h0ICogMC44ICsgd2luZG93LmlubmVySGVpZ2h0ICogMC4xLAogICAgICAgICAgICAgICAgICAgIGJ1YmJsZXM6IHRydWUKICAgICAgICAgICAgICAgIH0pOwogICAgICAgICAgICAgICAgZG9jdW1lbnQuYm9keS5kaXNwYXRjaEV2ZW50KGV2dCk7CiAgICAgICAgICAgICcnJykKICAgICAgICAKICAgICAgICAjIFN0YXkgb24gcGFnZSBhIGJpdCBtb3JlCiAgICAgICAgdGltZS5zbGVlcChyYW5kb20udW5pZm9ybSgxLCAzKSkKICAgICAgICAKICAgIGV4Y2VwdDoKICAgICAgICBwYXNzCgpkZWYgd29ya2VyKHdpZCwgdGFyZ2V0X3VybCwgbWF4X3Zpc2l0cywgc3RhcnRfdGltZSwgcHJveGllcyk6CiAgICBnbG9iYWwgdmlzaXRfY291bnQsIGVycm9yX2NvdW50CiAgICAKICAgIHZpc2l0c190aGlzX2Jyb3dzZXIgPSAwCiAgICBtYXhfcGVyX2Jyb3dzZXIgPSByYW5kb20ucmFuZGludCgxNSwgMzApCiAgICBwYWdlID0gTm9uZQogICAgCiAgICB3aGlsZSBUcnVlOgogICAgICAgIHdpdGggbG9jazoKICAgICAgICAgICAgaWYgdmlzaXRfY291bnQgPj0gbWF4X3Zpc2l0czoKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgCiAgICAgICAgaWYgcGFnZSBpcyBOb25lIG9yIHZpc2l0c190aGlzX2Jyb3dzZXIgPj0gbWF4X3Blcl9icm93c2VyOgogICAgICAgICAgICBpZiBwYWdlOgogICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIHBhZ2UucXVpdCgpCiAgICAgICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICBwcm94eSA9IHJhbmRvbS5jaG9pY2UocHJveGllcykgaWYgcHJveGllcyBlbHNlIE5vbmUKICAgICAgICAgICAgcGFnZSA9IGNyZWF0ZV9icm93c2VyKHByb3h5KQogICAgICAgICAgICBpZiBwYWdlIGlzIE5vbmU6CiAgICAgICAgICAgICAgICB3aXRoIGxvY2s6CiAgICAgICAgICAgICAgICAgICAgZXJyb3JfY291bnQgKz0gMQogICAgICAgICAgICAgICAgdGltZS5zbGVlcCgxKQogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgdmlzaXRzX3RoaXNfYnJvd3NlciA9IDAKICAgICAgICAgICAgbWF4X3Blcl9icm93c2VyID0gcmFuZG9tLnJhbmRpbnQoMTUsIDMwKQogICAgICAgIAogICAgICAgIHRyeToKICAgICAgICAgICAgIyBTZXQgcmFuZG9tIHJlZmVycmVyCiAgICAgICAgICAgIHJlZiA9IHJhbmRvbS5jaG9pY2UoUkVGRVJSRVJTKQogICAgICAgICAgICBpZiByZWY6CiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgcGFnZS5ydW5fanMoZidPYmplY3QuZGVmaW5lUHJvcGVydHkoZG9jdW1lbnQsICJyZWZlcnJlciIsIHt7Z2V0OiAoKSA9PiAie3JlZn0ifX0pJykKICAgICAgICAgICAgICAgIGV4Y2VwdDoKICAgICAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgICAgIAogICAgICAgICAgICAjIFJlLWluamVjdCBzdGVhbHRoIEpTIGJlZm9yZSBlYWNoIG5hdmlnYXRpb24KICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgaXNfbW9iaWxlID0gJ2lQaG9uZScgaW4gKHBhZ2UuX3VzZXJfYWdlbnQgb3IgJycpIG9yICdBbmRyb2lkJyBpbiAocGFnZS5fdXNlcl9hZ2VudCBvciAnJykKICAgICAgICAgICAgICAgIHJlcyA9IHJhbmRvbS5jaG9pY2UoU0NSRUVOX1JFU09MVVRJT05TKQogICAgICAgICAgICAgICAganMgPSBTVEVBTFRIX0pTLnJlcGxhY2UoJ19fU1dfXycsIHN0cihyZXNbMF0pKQogICAgICAgICAgICAgICAganMgPSBqcy5yZXBsYWNlKCdfX1NIX18nLCBzdHIocmVzWzFdKSkKICAgICAgICAgICAgICAgIGpzID0ganMucmVwbGFjZSgnX19DT1JFU19fJywgc3RyKHJhbmRvbS5jaG9pY2UoWzQsIDgsIDEyLCAxNl0pKSkKICAgICAgICAgICAgICAgIGpzID0ganMucmVwbGFjZSgnX19NRU1PUllfXycsIHN0cihyYW5kb20uY2hvaWNlKFs0LCA4LCAxNl0pKSkKICAgICAgICAgICAgICAgIGpzID0ganMucmVwbGFjZSgnX19UT1VDSF9fJywgc3RyKHJhbmRvbS5yYW5kaW50KDEsIDUpIGlmIGlzX21vYmlsZSBlbHNlIDApKQogICAgICAgICAgICAgICAgcGFnZS5ydW5fanMoanMpCiAgICAgICAgICAgIGV4Y2VwdDoKICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgCiAgICAgICAgICAgICMgTmF2aWdhdGUgdG8gdGFyZ2V0CiAgICAgICAgICAgIHBhZ2UuZ2V0KHRhcmdldF91cmwpCiAgICAgICAgICAgIAogICAgICAgICAgICAjIEh1bWFuIGJlaGF2aW9yIChzY3JvbGwsIG1vdXNlLCB3YWl0KQogICAgICAgICAgICBodW1hbl9iZWhhdmlvcihwYWdlKQogICAgICAgICAgICAKICAgICAgICAgICAgd2l0aCBsb2NrOgogICAgICAgICAgICAgICAgaWYgdmlzaXRfY291bnQgPCBtYXhfdmlzaXRzOgogICAgICAgICAgICAgICAgICAgIHZpc2l0X2NvdW50ICs9IDEKICAgICAgICAgICAgICAgICAgICBjdXJyZW50ID0gdmlzaXRfY291bnQKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgCiAgICAgICAgICAgIHZpc2l0c190aGlzX2Jyb3dzZXIgKz0gMQogICAgICAgICAgICAKICAgICAgICAgICAgaWYgY3VycmVudCAlIDUgPT0gMDoKICAgICAgICAgICAgICAgIHdyaXRlX3N0YXR1cyhtYXhfdmlzaXRzLCBzdGFydF90aW1lLCAicnVubmluZyIpCiAgICAgICAgICAgICAgICAKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIHdpdGggbG9jazoKICAgICAgICAgICAgICAgIGVycm9yX2NvdW50ICs9IDEKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgcGFnZS5xdWl0KCkKICAgICAgICAgICAgZXhjZXB0OgogICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICBwYWdlID0gTm9uZQogICAgICAgICAgICB0aW1lLnNsZWVwKDAuNSkKICAgIAogICAgaWYgcGFnZToKICAgICAgICB0cnk6CiAgICAgICAgICAgIHBhZ2UucXVpdCgpCiAgICAgICAgZXhjZXB0OgogICAgICAgICAgICBwYXNzCgpkZWYgcnVuX2F0dGFjayh0YXJnZXRfdXJsLCBtYXhfdmlzaXRvcnM9MTAwLCBwcm94aWVzPU5vbmUpOgogICAgZ2xvYmFsIHZpc2l0X2NvdW50LCBlcnJvcl9jb3VudAogICAgdmlzaXRfY291bnQgPSAwCiAgICBlcnJvcl9jb3VudCA9IDAKCiAgICBudW1fdGhyZWFkcyA9IG1pbigxNSwgbWF4KDMsIG1heF92aXNpdG9ycyAvLyAxMCkpCgogICAgc3RhcnRfdGltZSA9IHRpbWUudGltZSgpCiAgICB3cml0ZV9zdGF0dXMobWF4X3Zpc2l0b3JzLCBzdGFydF90aW1lLCAic3RhcnRpbmciKQoKICAgIHByb3h5X2luZm8gPSBmIiB8IFByb3hpZXM6IHtsZW4ocHJveGllcyl9IiBpZiBwcm94aWVzIGVsc2UgIiB8IE5vIHByb3h5IgogICAgcHJpbnQoZiJTdGFydGluZzoge21heF92aXNpdG9yc30gdmlzaXRvcnMgfCB7bnVtX3RocmVhZHN9IHRocmVhZHN7cHJveHlfaW5mb30gfCBTVEVBTFRIIE1PREUiLCBmbHVzaD1UcnVlKQoKICAgIHRocmVhZHMgPSBbXQogICAgZm9yIGkgaW4gcmFuZ2UobnVtX3RocmVhZHMpOgogICAgICAgIHQgPSB0aHJlYWRpbmcuVGhyZWFkKHRhcmdldD13b3JrZXIsIGFyZ3M9KGksIHRhcmdldF91cmwsIG1heF92aXNpdG9ycywgc3RhcnRfdGltZSwgcHJveGllcyBvciBbXSkpCiAgICAgICAgdC5kYWVtb24gPSBUcnVlCiAgICAgICAgdC5zdGFydCgpCiAgICAgICAgdGhyZWFkcy5hcHBlbmQodCkKICAgICAgICB0aW1lLnNsZWVwKDAuNSkKCiAgICB3aGlsZSBhbnkodC5pc19hbGl2ZSgpIGZvciB0IGluIHRocmVhZHMpOgogICAgICAgIHdyaXRlX3N0YXR1cyhtYXhfdmlzaXRvcnMsIHN0YXJ0X3RpbWUsICJydW5uaW5nIikKICAgICAgICB0aW1lLnNsZWVwKDIpCgogICAgZm9yIHQgaW4gdGhyZWFkczoKICAgICAgICB0LmpvaW4odGltZW91dD01KQoKICAgIHdyaXRlX3N0YXR1cyhtYXhfdmlzaXRvcnMsIHN0YXJ0X3RpbWUsICJmaW5pc2hlZCIpCiAgICBwcmludChmIkZpbmlzaGVkISBUb3RhbDoge3Zpc2l0X2NvdW50fSB2aXNpdHMgfCBFcnJvcnM6IHtlcnJvcl9jb3VudH0iLCBmbHVzaD1UcnVlKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHVybCA9IHN5cy5hcmd2WzFdIGlmIGxlbihzeXMuYXJndikgPiAxIGVsc2UgImh0dHA6Ly9leGFtcGxlLmNvbSIKICAgIHZpc2l0b3JzID0gaW50KHN5cy5hcmd2WzJdKSBpZiBsZW4oc3lzLmFyZ3YpID4gMiBlbHNlIDEwMAogICAgcHJveHlfZmlsZSA9IHN5cy5hcmd2WzNdIGlmIGxlbihzeXMuYXJndikgPiAzIGVsc2UgTm9uZQoKICAgIHByb3hpZXMgPSBbXQogICAgaWYgcHJveHlfZmlsZToKICAgICAgICB0cnk6CiAgICAgICAgICAgIHdpdGggb3Blbihwcm94eV9maWxlLCAncicpIGFzIGY6CiAgICAgICAgICAgICAgICBwcm94aWVzID0ganNvbi5sb2FkKGYpCiAgICAgICAgICAgIHByaW50KGYiTG9hZGVkIHtsZW4ocHJveGllcyl9IHByb3hpZXMiLCBmbHVzaD1UcnVlKQogICAgICAgIGV4Y2VwdDoKICAgICAgICAgICAgcHJpbnQoIkZhaWxlZCB0byBsb2FkIHByb3hpZXMiLCBmbHVzaD1UcnVlKQoKICAgIHJ1bl9hdHRhY2sodXJsLCB2aXNpdG9ycywgcHJveGllcyBpZiBwcm94aWVzIGVsc2UgTm9uZSkK";

const SETUP_COMMAND = 'export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y python3 python3-pip wget gnupg2 libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 fonts-liberation xdg-utils && (apt-get install -y libasound2 2>/dev/null || apt-get install -y libasound2t64 2>/dev/null || true) && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt-get install -y ./google-chrome-stable_current_amd64.deb 2>/dev/null; rm -f google-chrome-stable_current_amd64.deb && pip3 install DrissionPage --break-system-packages 2>/dev/null || pip3 install DrissionPage && echo SETUP_COMPLETE';

async function runSSHCommand(server, command, timeout = 15000) {
  return new Promise((resolve) => {
    const conn = new Client();
    let output = '';
    let resolved = false;

    const done = (result) => {
      if (!resolved) {
        resolved = true;
        try { conn.end(); } catch(e) {}
        resolve(result);
      }
    };

    const timer = setTimeout(() => {
      done({ status: 'success', output: output.trim() || 'Command sent (timeout)' });
    }, timeout);

    conn.on('ready', () => {
      conn.exec(command, { pty: false }, (err, stream) => {
        if (err) {
          clearTimeout(timer);
          return done({ status: 'error', error: err.message });
        }

        stream.on('data', (data) => {
          output += data.toString();
        });

        stream.stderr.on('data', (data) => {
          // ignore stderr
        });

        stream.on('close', () => {
          clearTimeout(timer);
          done({ status: 'success', output: output.trim() || 'Done' });
        });
      });
    });

    conn.on('error', (err) => {
      clearTimeout(timer);
      done({ status: 'error', error: err.message });
    });

    conn.connect({
      host: server.host,
      port: 22,
      username: server.username,
      password: process.env.VPS_PASSWORD,
      readyTimeout: 10000,
      keepaliveInterval: 5000,
    });
  });
}

export async function POST(req) {
  try {
    const { action, url, visitors, duration, servers, proxies } = await req.json();
    const serverList = (servers && servers.length > 0) ? servers : DEFAULT_SERVERS;

    if (action === 'setup') {
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, `nohup bash -c '${SETUP_COMMAND}' > /root/setup.log 2>&1 & echo "Setup started"`, 15000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'deploy') {
      const command = `echo "${PYTHON_SCRIPT_B64}" | base64 -d > /root/visit.py && echo "Script deployed"`;
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, command, 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'start') {
      if (!url) return NextResponse.json({ error: "URL is required" }, { status: 400 });
      const totalVisitors = visitors || 100;
      const serverCount = serverList.length;
      // Divide total visitors across all servers
      const perServer = Math.ceil(totalVisitors / serverCount);

      // Step 1: Kill old processes and clean up on all servers
      await Promise.all(
        serverList.map(async (server) => {
          await runSSHCommand(server, 'kill -9 $(pgrep -f "visit.py") 2>/dev/null; killall -9 chrome 2>/dev/null; killall -9 chromium 2>/dev/null; rm -f /root/visit_status.json /root/visit.log; echo "Cleaned"', 8000);
        })
      );

      // Step 2: Deploy latest script
      await Promise.all(
        serverList.map(async (server) => {
          await runSSHCommand(server, `echo "${PYTHON_SCRIPT_B64}" | base64 -d > /root/visit.py && echo "Deployed"`, 8000);
        })
      );

      // Step 3: Start at MAX SPEED - no time limit, stops when target reached
      const results = await Promise.all(
        serverList.map(async (server) => {
          let startCmd;
          if (proxies && proxies.length > 0) {
            const proxyB64 = Buffer.from(JSON.stringify(proxies)).toString('base64');
            startCmd = `echo "${proxyB64}" | base64 -d > /root/proxies.json && nohup python3 /root/visit.py "${url}" ${perServer} /root/proxies.json > /root/visit.log 2>&1 & echo "Started PID=$!"`;
          } else {
            startCmd = `nohup python3 /root/visit.py "${url}" ${perServer} > /root/visit.log 2>&1 & echo "Started PID=$!"`;
          }
          const r = await runSSHCommand(server, startCmd, 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else if (action === 'stop') {
      const results = await Promise.all(
        serverList.map(async (server) => {
          const r = await runSSHCommand(server, 'kill -9 $(pgrep -f "visit.py") 2>/dev/null; killall -9 chrome 2>/dev/null; killall -9 chromium 2>/dev/null; rm -f /root/visit_status.json; echo "Stopped"', 10000);
          return { host: server.host, ...r };
        })
      );
      return NextResponse.json({ results });

    } else {
      return NextResponse.json({ error: "Unknown action" }, { status: 400 });
    }
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
